@baseUrl = http://localhost:3333
@lastShortUrlId = {{generate_short_url.response.body.shortUrlId}}

# @name generate_short_url
POST {{baseUrl}}/api/short
Content-Type: application/json

{
  "originalUrl": "http://vepifaniodev.com"
}

###
# @name get_original_url
GET {{baseUrl}}/{{lastShortUrlId}}