services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
